name: RLMeshV2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - absl-py==2.3.1
      - ale-py==0.11.2
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - exceptiongroup==1.3.1
      - Farama-Notifications==0.0.4
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - grpcio==1.76.0
      - gymnasium==1.2.2
      - iniconfig==2.3.0
      - Jinja2==3.1.6
      - kiwisolver==1.4.9
      - Markdown==3.10
      - markdown-it-py==4.0.0
      - MarkupSafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - pluggy==1.6.0
      - protobuf==6.33.1
      - psutil==7.1.3
      - pygame==2.6.1
      - Pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==9.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rich==14.2.0
      - seaborn==0.13.2
      - Shimmy==2.0.0
      - six==1.17.0
      - stable_baselines3==2.7.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tomli==2.3.0
      - tqdm==4.67.1
      - typing_extensions==4.15.0
      - tzdata==2025.2
      - Werkzeug==3.1.3
